version: '3.4'

services:
  nodesendmail:
    image: nodesendmail
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SERVICE=gmail
      - SENDER_USERNAME=
      - SENDER_PASSWORD=
      - SENDER_EMAIL=
      - RECIEVER_EMAIL=
      - SUBJECT=Hello Test!
      - CONTENT=<h1>Hi!</h1><p>This is content.</p><h5>Goodbye!</h5>
